# Adapted from https://github.com/pandas-dev/pandas/blob/master/azure-pipelines.yml
jobs:

# - template: continuous_integration/windows.yml
#   parameters:
#     name: Windows
#     vmImage: vs2017-win2016
#     matrix:
#       py38_pip:
#         VERSION_PYTHON: '3.8'
#         PACKAGER: 'pip'
#       py37_conda:
#         VERSION_PYTHON: '3.7'
#         PACKAGER: 'conda'
#       py37_pip:
#         VERSION_PYTHON: '3.7'
#         PACKAGER: 'pip'
#       py36_pip:
#         VERSION_PYTHON: '3.6'
#         PACKAGER: 'pip'

- template: continuous_integration/posix.yml
  parameters:
    name: Linux
    vmImage: ubuntu-18.04
    matrix:
      py36_ubuntu:
        PACKAGER: 'ubuntu'
        VERSION_PYTHON: '3.6'
      py36_conda:
        PACKAGER: 'conda'
        VERSION_PYTHON: '3.6'
        COVERAGE: 'true'
        TOKEN: $(CODECOV_TOKEN)
      pylatest_conda:
        PACKAGER: 'conda'
        VERSION_PYTHON: '*'

- template: continuous_integration/posix.yml
  parameters:
    name: macOS
    vmImage: macOS-10.14
    matrix:
      pylatest_conda:
        VERSION_PYTHON: '*'
        PACKAGER: 'conda'
